name: main_workflow
on: 
  push:
    branches:
      - node_jest_job
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: nodejs_linter_job
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          VALIDATE_JAVASCRIPT_ES: true
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          LINTER_RULES_PATH: /
  test-execution:
    runs-on: ubuntu-latest
    needs: linter-execution
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Jest
        run: npm install jest
      - name: Run Jest Test
        id: jest
        run: |
          mkdir ${{ runner.temp }}/build.logs
          npm run test --log-path ${{ runner.temp }}/build.logs
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        if: ${{ failure() }}
        with: 
          server_address: smtp.email.com
          server_port: 465
          secure: true
          subject: Resultado Tests Jest
          to: daw.moisesguerola@gmail.com
          from: Mois√©s Guerola
          body: Test del ${{ github.repository }} han fallado!